---
title: "R Notebook"
output: html_notebook
---

Here are come plots to work with 

```{r}
library(ggplot2)
p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp,)) + 
  ggtitle('Plot 1')

p2 <- ggplot(mtcars) + 
  geom_boxplot(aes(gear, disp, group = gear, fill=as.character(gear))) + 
  ggtitle('Plot 2') + 
    guides(fill = guide_legend(title = 'gear'))

p3 <- ggplot(mtcars) + 
  geom_point(aes(hp, wt, colour = mpg)) + 
  ggtitle('Plot 3')

p4 <- ggplot(mtcars) + 
  geom_bar(aes(gear)) + 
  facet_wrap(~cyl) + 
  ggtitle('Plot 4')
```

- add the plots together one by one, no orientation

```{r fig.height=8, fig.width=8}
library(patchwork)


```

- add plots, but make only one column of plots 

```{r, fig.width=4, fig.height=10}


```

- use a desgin and `plot_layout` to make plot 1 bigger than the rest of the plots 

```{r}
design <- '
AAAB
AAAC
AAAD
'

all_plots + plot_layout(design = design, guides = 'collect') & theme(legend.position = 'top')
```


```{r}
install.packages(c('plotly', 'ggiraph'), type = 'source')

```


- make this an interactive plot with `girafe`, displaying the carb column 

```{r}
library(ggiraph) 
library(tidyverse)
 
plot_interactive <-  ggplot(mtcars) + 
  geom_point(aes(hp, wt, colour = mpg)) + 
  ggtitle('Plot 3')

girafe(ggobj = plot_interactive)
```

remake the above plot with plotly

```{r}
library(plotly)

```










