---
title: "make_dummy_data"
output: html_notebook
---

```{r}
dummy_data = tibble(Time = c(rep(0,5), rep(3, 5), rep(5, 5), rep(8, 5), rep(24, 5)), 
                    Replicate= rep(c(1, 2, 3, 4, 5), 5),
                    WildType = c(rep(0,5),  rnorm(5, 4, 1.4), rnorm(5, 6, 1.6), rnorm(5, 9, 1.1) , rnorm(5, 10, 1.8)),
                    Mutant = c(rep(0,5),rnorm(5, 4, 1.7), rnorm(5, 8, 1.3), rnorm(5, 15, 1) , rnorm(5, 20, 1.2))
                    )
write_tsv(dummy_data, '../src/Reporter_assay_results.tsv.gz')
long_data <- dummy_data %>% pivot_longer(c(WildType, Mutant), names_to = 'type', values_to = 'SU') 
sum_data <- long_data%>% 
 group_by(Time, type) %>% 
    summarise(avg_su = mean(SU), 
              sd_su = sd(SU), 
              n=n(), 
              ) %>% 
    mutate(err = sd_su/sqrt(n)) #%>% 

ggplot() + 
    geom_vline(xintercept = 8, color = 'red' )+
    ggrepel::geom_label_repel(data = NULL, aes(x=c(8), y=c(12), label='Reaction Temperature\ndecreased'), nudge_x = 6, nudge_y =.5  )+
    geom_errorbar(data = sum_data,  aes(x=Time, ymax = avg_su + err, ymin = avg_su-err), width = .4)+
    geom_line(data = sum_data, aes(x=Time, y=avg_su, color = type)) +
    scale_shape_manual(values = c('Mutant' =16, 'WildType' = 18)) + 
    geom_point(data = sum_data, aes(x=Time, y=avg_su, shape = type, color =type ), size= 3) + 
    ggtitle('Enzymatic Activity of Protein X') + 
    ylab('Scientific Units(SU)') + 
    xlab('Time(hours)')+
    theme_classic()  + 
    theme(panel.grid.major = element_line(size=.2), 
          panel.grid.minor = element_line(size = .2))
ggsave('../src/reporter_assay_plot.png')
```



```{r}
library(Seurat)
library(tidyverse)
pbmc <- readRDS(file = "~/Downloads/pbmc3k_final.rds")
pbmc <-  Seurat::RunPCA(pbmc)
pbmc <- Seurat::RunUMAP(pbmc, dims = 1:30)
pbmc$groups <- sample(c("group1", "group2"), size = ncol(pbmc), replace = TRUE)
features <- c("LYZ", "CCL5", "IL32", "PTPRCAP", "FCGR3A", "PF4")
pbmc
t_feat <-  pbmc@assays$RNA@var.features %>% head(10)
cell_types <- pbmc@active.ident %>% {tibble(barcode  = names(.), cell_type = .)}
umap <- pbmc@reductions$umap@cell.embeddings %>% as.data.frame(col.names = c('UMAP1','UMAP2')) %>% rownames_to_column('barcode')
raw_data <- pbmc@assays$RNA@data[t_feat, ] %>% 
    as.data.frame %>% 
    t() %>% 
    as.data.frame %>% 
    rownames_to_column('barcode') %>% 
    left_join(umap,.) %>% 
    left_join(cell_types,.) %>% 
    mutate(patient_id = sample(c('patient_1', 'patient_2', 'patient_3'), replace = T, size = nrow(.)),
           cell_type_relabeled = sample(.$cell_type, size = nrow(.), replace = T)) %>% 
    select(barcode, cell_type, cell_type_relabeled, patient_id, everything()) 

write_tsv(raw_data, '../src/pbmc_cell_expression.tsv.gz')
```



```{r}
k <- read_tsv('../src/tx_expression_subset.tsv.gz')
gtf <- rtracklayer::readGFF('~/Downloads/gencode.v35.annotation.gtf.gz')
tx2gene <- gtf %>% filter(type == 'transcript', transcript_id %in% k$transcript_id) %>% left_join(k, .) %>%   select(gene_name,transcript_id) %>% mutate(gene_name = replace(gene_name,                                                                                                list = is.na(gene_name),
                                                                     values = sample(gtf$gene_name, sum(is.na(gene_name)))  ) )

neg_p <-  rnorm(n=10000, .5, sd = .2) %>% {sample(.[between(., .05, 1)], 5000, replace = T)}
neg_l2fc <- rnorm(n=10000, 0, .2) %>% {sample(.[between(., .-1, 1)], 5000, replace = T)}

pos_p <- rnorm(n=10000, .5, sd = .4) %>% {sample(.[between(., 0, .0499)], n_distinct(tx2gene$gene_name), replace = T)}
pos_l2fc <- rnorm(n=10000, .5, sd = .5) %>% {sample(.[.>1 | . < -1], n_distinct(tx2gene$gene_name), replace = T)}

volcano_data <- bind_rows(
  tibble(gene_name = sample(unique(gtf$gene_name), 5000, replace = F), 
         pvalue = neg_p, 
         log2fc = neg_l2fc),
  tibble(gene_name = unique(tx2gene$gene_name), 
         pvalue = pos_p,
         log2fc = pos_l2fc
         )
) %>% mutate(significant = ifelse(pvalue <.05& (log2fc > 1 | log2fc < -1),'sig', 'not_sig'))
write_tsv(volcano_data, '../src/diff_gene_exp.tsv.gz')
sum(volcano_data$significant == 'sig')
```


