---
title: "Technical Report"
output:
  html_document:
    df_print: paged
---



```{r}
file_to_process <- '../src/pbmc_cell_expression.tsv.gz'
```


```{r, include = F}

library(tidyverse)
library(knitr)

data <- read_tsv(file_to_process)


df <- data %>% group_by(`Cell Type` = cell_type) %>% summarise(`Cell count` = n(), 
                                           `Cells from Patient 1` = sum(patient_id == 'patient_1'),
                                           `Cells from Patient 2`  = sum(patient_id == 'patient_2'),
                                           `Cells from Patient 3`  = sum(patient_id == 'patient_3') )

```

```{r}
kable(df)
```


`echo = F`  - code not printed out
`include = F` - all output suppressed
`fig.height` - plot output height 


```{r, include = F}
pca_data <-  prcomp(data[,5:14])
pca_x <- pca_data$x[,1:2] %>% as.data.frame
colnames(pca_x) <- c('PC1', 'PC2')
pca_df <- bind_cols(pca_x, data)
sum_pca <- summary(pca_data)
pc1_prop <- round(sum_pca$importance[2, 1], digits = 2)*100
pc2_prop <- round(sum_pca$importance[2, 2], digits = 2)*100

```

```{r}
ggplot(pca_df) + 
    geom_point(aes(x=PC1, y=PC2, color = cell_type)) + 
    xlab(paste0('PC1 (', pc1_prop,  ' percent of variance explained)') )+
    ylab(paste0('PC2 (', pc2_prop,  ' percent of variance explained)') )+
    guides(color = guide_legend(title = 'Cell Type')) + 
    ggtitle('PCA generated from selected genes')+
    theme_minimal()
```



```{r, echo = F, }
dp_data <- data %>% 
    pivot_longer(-colnames(data)[1:4], names_to= 'gene_name', values_to = 'exp') %>% 
    group_by(cell_type, gene_name) %>% 
    summarise(avg_exp = mean(exp), 
                n_expressing = sum(exp > 0), 
                pt_expressing = n_expressing/ n() *100)
ggplot(dp_data) + 
    geom_point(aes(x=gene_name, y= cell_type, color = avg_exp, size = pt_expressing)) + 
    scale_color_viridis_c() + 
    xlab('') +
    ylab('') + 
    guides(color = guide_legend(title = 'Average Expression'),
           size = guide_legend(title = "% expressing"))+
    theme_classic()

```



```{r,fig.cap="Some caption" }

```

