---
title: "R Notebook"
output: html_notebook
---

Here are come plots to work with 

```{r}
library(ggplot2)
p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp,)) + 
  ggtitle('Plot 1')

p2 <- ggplot(mtcars) + 
  geom_boxplot(aes(gear, disp, group = gear, fill=as.character(gear))) + 
  ggtitle('Plot 2') + 
    guides(fill = guide_legend(title = 'gear'))

p3 <- ggplot(mtcars) + 
  geom_point(aes(hp, wt, colour = mpg)) + 
  ggtitle('Plot 3')

p4 <- ggplot(mtcars) + 
  geom_bar(aes(gear)) + 
  facet_wrap(~cyl) + 
  ggtitle('Plot 4')
```

- add the plots together one by one, no orientation

```{r}
install.packages('patchwork')


p1+p2+p3+p4
```

- add plots, but make only one column of plots 

```{r, fig.width=4, fig.height=10}
library(patchwork)
p1+p2 +p3 +p4 + plot_layout(ncol = 1)
```

- use a desgin and `plot_layout` to make plot 1 bigger than the rest of the plots 

```{r}
des <-'
ABB
CCC
DDD'


des <- '
AAAABB
AAAABB
AAAACC
AAAACC
DDDDDD
DDDDDD'
p1+p2 +p3 +p4 + plot_layout(design = des) + plot_annotation(tag_levels = 'A')
?plot_annotation
```


```{r}

```


- make this an interactive plot with `girafe`, displaying the carb column 

```{r}
library(ggiraph) 
library(tidyverse)
 

```

remake the above plot with plotly

```{r}
library(plotly)

```










